apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec: 
  containers:
  - name: demo
    image: alpine
    cpmmand: ["sleep", "3600"]
    env: 
    - name: player_initial_lives
      valueFrom:
        configMapkeyRef:
          name: game-demo
          key: player_initial_lives